=== ivanChernik/EPAM-task3.1-SAX-StAX/src/by/epam/tc/parser/xml/menuXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.tc.com/menuXMLSchema"
	xmlns:m="http://www.epam.tc.com/menuXMLSchema">
	<element name="menu-list">
		<complexType>
			<sequence>
				<element name="cold-appetizers" type="m:ColdAppetizer" />
				<element name="hot-appetizers" type="m:HotAppetizer" />
				<element name="breakfasts" type="m:Breakfast" />
			</sequence>
		</complexType>
	</element>
	<complexType name="ColdAppetizer">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="cold-appetizer" type="m:Dish" />
		</sequence>
	</complexType>
	<complexType name="HotAppetizer">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="hot-appetizer" type="m:Dish" />
		</sequence>
	</complexType>
	<complexType name="Breakfast">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="breakfast" type="m:Dish" />
		</sequence>
	</complexType>
	<complexType name="Dish">
		<sequence>
			<element name="name" type="string" />
			<choice minOccurs="0" maxOccurs="1">
				<element name="description" type="string" />
			</choice>
			<choice minOccurs="0" maxOccurs="1">
				<element name="portion" type="string" />
			</choice>
			<choice minOccurs="0" maxOccurs="1">
				<element name="price" type="integer" />
			</choice>
		</sequence>
		<attribute name="id" type="m:Id" use="required" />
	</complexType>
	<simpleType name="Id">
		<restriction base="string">
			<pattern value="[0-9]+" />
		</restriction>
	</simpleType>
</schema>

=== ivanChernik/EPAM-task3.1-SAX-StAX/src/by/epam/tc/parser/xml/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<m:menu-list xmlns:m="http://www.epam.tc.com/menuXMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.epam.tc.com/menuXMLSchema menuXMLSchema.xsd">
	<cold-appetizers>
		<cold-appetizer id="1">
			<name>Ассорти рыбное</name>
			<description>Слабосоленая форель, семга</description>
			<portion>100/20/15</portion>
		</cold-appetizer>
		<cold-appetizer id="2">
			<name>Овощной букет</name>
			<description>Корейская морковь,капустаю фунчоза</description>
			<portion>100/20/15</portion>
		</cold-appetizer>
		<cold-appetizer id="3">
			<name>Соленья по-домашнему</name>
			<description>Маринованные овощи</description>
			<portion>150/10</portion>
		</cold-appetizer>
	</cold-appetizers>
	<hot-appetizers>
		<hot-appetizer id="4">
			<name>Лобио с шампинтонами</name>
			<description>Фасоль с шампиньонами,грецкий орех, фунчоза</description>
			<portion>100/20/15</portion>
			<price>105</price>
		</hot-appetizer>
		<hot-appetizer id="5">
			<name>Мидии по-турецки</name>
			<description>Мидии, сыр, грецкий орех</description>
			<portion>150/30</portion>
			<price>190</price>
		</hot-appetizer>
		<hot-appetizer id="6">
			<name>Эскарго</name>
			<description>Виноградные улитки по бургундски</description>
			<portion>12</portion>
			<price >230</price>
		</hot-appetizer>
	</hot-appetizers>
	<breakfasts>
		<breakfast id="7">
			<name>Глазунья</name>
			<description>Яйца</description>
			<portion>150</portion>
		</breakfast>
		<breakfast id="8">
			<name>Омлет</name>
			<portion>100</portion>
		</breakfast>	
		<breakfast id="9">
			<name>Блинчики с мясом</name>
			<description>Жаренные блинчики с мясом</description>
			<portion>150</portion>
		</breakfast>	
	</breakfasts>
</m:menu-list>
